In [25]:
from tqdm import tqdm
import pandas as pd
import requests as r
from bs4 import BeautifulSoup as bs

In [2]:
cardsUrl ="https://www.deckshop.pro/card/list"
response =r.get(cardsUrl)

In [3]:
with open("CardsUrl.html","w") as file:
    file.write(response.text)

In [27]:
baseUrl = "https://www.deckshop.pro"
with open ("CardsUrl.html","r") as file:
    sourceCode = file.read()
    soup = bs(sourceCode, "html.parser")
    cardsUrls = soup.find_all("img",{"class":"card"})
    cardDictioanry = {"Cards Name":[],"Cards Image Urls": []}
    for eachUrl in tqdm( cardsUrls,desc="Downloading Cards",unit="img"):
        cardDictioanry["Cards Name"].append( eachUrl.get("src").split("/")[-1].split(".")[0])
        cardDictioanry["Cards Image Urls"].append(eachUrl.get("src"))
        # tqdm.write(f"Downloading {eachUrl.get('src').split('/')[-1]}...")
        downloadedImage = r.get(baseUrl+eachUrl.get("src"))
        with open("CardsDownload/"+eachUrl.get("src").split("/")[-1],"wb") as img:

            img.write(downloadedImage.content)
    cardDataFrame = pd.DataFrame(cardDictioanry)
    cardDataFrame

Downloading Cards:  22%|██▏       | 118/529 [00:18<01:04,  6.34img/s]

KeyboardInterrupt:

In [20]:
cardDataFrame

      Cards Name                Cards Image Urls
0       Skellies   /img/card_ed_evo/Skellies.png
1      IceSpirit  /img/card_ed_evo/IceSpirit.png
2         Bomber     /img/card_ed_evo/Bomber.png
3           Bats       /img/card_ed_evo/Bats.png
4            Zap        /img/card_ed_evo/Zap.png
..           ...                             ...
524  MightyMiner    /img/card_ed/MightyMiner.png
525  ArcherQueen    /img/card_ed/ArcherQueen.png
526  Goblinstein    /img/card_ed/Goblinstein.png
527         Monk           /img/card_ed/Monk.png
528   BossBandit     /img/card_ed/BossBandit.png

[529 rows x 2 columns]

In [29]:
response = r.get("https://fake-json-api.mock.beeceptor.com/users")
print(response.text)

[
  {
    "id": 1,
    "name": "Lafayette Keeling",
    "company": "Ullrich - Yundt",
    "username": "Isac33",
    "email": "Manuela1@yahoo.com",
    "address": "70163 Dawn Rapid",
    "zip": "89888-6895",
    "state": "Maine",
    "country": "Guinea-Bissau",
    "phone": "744-643-5340 x3150",
    "photo": "https://json-server.dev/ai-profiles/46.png"
  },
  {
    "id": 2,
    "name": "Justen Faker Attribute Error: person.astName is not supported",
    "company": "Reichel - Franecki",
    "username": "Guy_Quigley71",
    "email": "Dax.Smitham@gmail.com",
    "address": "4543 Glenda Falls",
    "zip": "23885-2397",
    "state": "New Jersey",
    "country": "Cote d&#x27;Ivoire",
    "phone": "1-272-353-4804 x2735",
    "photo": "https://json-server.dev/ai-profiles/96.png"
  },
  {
    "id": 3,
    "name": "Lydia Koss",
    "company": "Pfannerstill - Carroll",
    "username": "Pat39",
    "email": "Cleo_Treutel27@hotmail.com",
    "address": "636 Yost Plains",
    "zip": "24944",
    "state": "Florida",
    "country": "Haiti",
    "phone": "1-464-709-8369 x753",
    "photo": "https://json-server.dev/ai-profiles/24.png"
  },
  {
    "id": 4,
    "name": "Kira Oberbrunner",
    "company": "Pacocha - Franey",
    "username": "Yvette_Senger",
    "email": "Uriel_Bogisich@hotmail.com",
    "address": "24738 Poplar Avenue",
    "zip": "92108",
    "state": "Idaho",
    "country": "Morocco",
    "phone": "707.936.8817 x03872",
    "photo": "https://json-server.dev/ai-profiles/82.png"
  },
  {
    "id": 5,
    "name": "Jewel Ward",
    "company": "Reynolds - Dietrich",
    "username": "Jameson_Hettinger82",
    "email": "Jalyn.Bins@yahoo.com",
    "address": "773 W Jefferson Street",
    "zip": "63280",
    "state": "Alaska",
    "country": "Nigeria",
    "phone": "855.304.0986",
    "photo": "https://json-server.dev/ai-profiles/89.png"
  },
  {
    "id": 6,
    "name": "Alda Ondricka",
    "company": "Welch Inc",
    "username": "Celine_Rohan",
    "email": "Faye.Pagac-Steuber92@yahoo.com",
    "address": "6356 Schuster Vista",
    "zip": "60307-3738",
    "state": "Kentucky",
    "country": "Saint Lucia",
    "phone": "978.361.4949 x32978",
    "photo": "https://json-server.dev/ai-profiles/81.png"
  },
  {
    "id": 7,
    "name": "Lynn Johns-White",
    "company": "Batz and Sons",
    "username": "Mohammad.Cummerata",
    "email": "Hertha_Hammes@gmail.com",
    "address": "95586 Rectory Close",
    "zip": "15503-9574",
    "state": "Oregon",
    "country": "Andorra",
    "phone": "(738) 237-2278",
    "photo": "https://json-server.dev/ai-profiles/2.png"
  },
  {
    "id": 8,
    "name": "Franco Rolfson",
    "company": "Batz, Gerhold and Funk",
    "username": "Alex.Stamm40",
    "email": "Micaela94@hotmail.com",
    "address": "53623 Dare Via",
    "zip": "07306",
    "state": "Georgia",
    "country": "Solomon Islands",
    "phone": "(592) 859-2932",
    "photo": "https://json-server.dev/ai-profiles/45.png"
  },
  {
    "id": 9,
    "name": "Major Legros",
    "company": "Grimes and Sons",
    "username": "Amira.Osinski38",
    "email": "Derek_Spencer@yahoo.com",
    "address": "9826 Rectory Lane",
    "zip": "12160-3177",
    "state": "Minnesota",
    "country": "Gibraltar",
    "phone": "387.777.7644 x2221",
    "photo": "https://json-server.dev/ai-profiles/49.png"
  },
  {
    "id": 10,
    "name": "Clara Braun",
    "company": "Ebert, Reynolds and Streich",
    "username": "Cheyenne84",
    "email": "Theresia57@hotmail.com",
    "address": "58514 Rutherford Streets",
    "zip": "34408-8676",
    "state": "Texas",
    "country": "Italy",
    "phone": "1-673-451-5461 x5126",
    "photo": "https://json-server.dev/ai-profiles/53.png"
  }
]

In [31]:
tableresponse = r.get("https://www.scrapethissite.com/pages/forms/")
with open("TableData.html","w") as file:
    file.write(tableresponse.text)

In [38]:
with open("TableData.html","r") as file:
    sourceCode = file.read()
    soup = bs(sourceCode,"html.parser")
    tableData = soup.find_all("tr")
    tableDataList = []
    for eachRow in tableData:
        cell = eachRow.find_all(["td","th"])
        tableDataList.append(cell)

In [39]:
tableDF = pd.DataFrame(tableDataList[1:],columns=tableDataList[0])

In [40]:
tableDF

,[\n Team Name\n ],[\n Year\n ],[\n Wins\n ],[\n Losses\n ],[\n OT Losses\n ],[\n Win %\n ],[\n Goals For (GF)\n ],[\n Goals Against (GA)\n ],[\n + / -\n ]
0,[\n Boston Bruins\n...,[\n 1990\n ...,[\n 44\n ...,[\n 24\n ...,[\n],[\n 0.55\n ...,[\n 299\n ...,[\n 264\n ...,[\n 35\n ...
1,[\n Buffalo Sabres\...,[\n 1990\n ...,[\n 31\n ...,[\n 30\n ...,[\n],[\n 0.388\n ...,[\n 292\n ...,[\n 278\n ...,[\n 14\n ...
2,[\n Calgary Flames\...,[\n 1990\n ...,[\n 46\n ...,[\n 26\n ...,[\n],[\n 0.575\n ...,[\n 344\n ...,[\n 263\n ...,[\n 81\n ...
3,[\n Chicago Blackha...,[\n 1990\n ...,[\n 49\n ...,[\n 23\n ...,[\n],[\n 0.613\n ...,[\n 284\n ...,[\n 211\n ...,[\n 73\n ...
4,[\n Detroit Red Win...,[\n 1990\n ...,[\n 34\n ...,[\n 38\n ...,[\n],[\n 0.425\n ...,[\n 273\n ...,[\n 298\n ...,[\n -25\n ...
5,[\n Edmonton Oilers...,[\n 1990\n ...,[\n 37\n ...,[\n 37\n ...,[\n],[\n 0.463\n ...,[\n 272\n ...,[\n 272\n ...,[\n 0\n ...
6,[\n Hartford Whaler...,[\n 1990\n ...,[\n 31\n ...,[\n 38\n ...,[\n],[\n 0.388\n ...,[\n 238\n ...,[\n 276\n ...,[\n -38\n ...
7,[\n Los Angeles Kin...,[\n 1990\n ...,[\n 46\n ...,[\n 24\n ...,[\n],[\n 0.575\n ...,[\n 340\n ...,[\n 254\n ...,[\n 86\n ...
8,[\n Minnesota North...,[\n 1990\n ...,[\n 27\n ...,[\n 39\n ...,[\n],[\n 0.338\n ...,[\n 256\n ...,[\n 266\n ...,[\n -10\n ...
9,[\n Montreal Canadi...,[\n 1990\n ...,[\n 39\n ...,[\n 30\n ...,[\n],[\n 0.487\n ...,[\n 273\n ...,[\n 249\n ...,[\n 24\n ...
10,[\n New Jersey Devi...,[\n 1990\n ...,[\n 32\n ...,[\n 33\n ...,[\n],[\n 0.4\n ...,[\n 272\n ...,[\n 264\n ...,[\n 8\n ...
11,[\n New York Island...,[\n 1990\n ...,[\n 25\n ...,[\n 45\n ...,[\n],[\n 0.312\n ...,[\n 223\n ...,[\n 290\n ...,[\n -67\n ...
12,[\n New York Ranger...,[\n 1990\n ...,[\n 36\n ...,[\n 31\n ...,[\n],[\n 0.45\n ...,[\n 297\n ...,[\n 265\n ...,[\n 32\n ...
13,[\n Philadelphia Fl...,[\n 1990\n ...,[\n 33\n ...,[\n 37\n ...,[\n],[\n 0.412\n ...,[\n 252\n ...,[\n 267\n ...,[\n -15\n ...
14,[\n Pittsburgh Peng...,[\n 1990\n ...,[\n 41\n ...,[\n 33\n ...,[\n],[\n 0.512\n ...,[\n 342\n ...,[\n 305\n ...,[\n 37\n ...
15,[\n Quebec Nordique...,[\n 1990\n ...,[\n 16\n ...,[\n 50\n ...,[\n],[\n 0.2\n ...,[\n 236\n ...,[\n 354\n ...,[\n -118\n ...
16,[\n St. Louis Blues...,[\n 1990\n ...,[\n 47\n ...,[\n 22\n ...,[\n],[\n 0.588\n ...,[\n 310\n ...,[\n 250\n ...,[\n 60\n ...
17,[\n Toronto Maple L...,[\n 1990\n ...,[\n 23\n ...,[\n 46\n ...,[\n],[\n 0.287\n ...,[\n 241\n ...,[\n 318\n ...,[\n -77\n ...
18,[\n Vancouver Canuc...,[\n 1990\n ...,[\n 28\n ...,[\n 43\n ...,[\n],[\n 0.35\n ...,[\n 243\n ...,[\n 315\n ...,[\n -72\n ...
19,[\n Washington Capi...,[\n 1990\n ...,[\n 37\n ...,[\n 36\n ...,[\n],[\n 0.463\n ...,[\n 258\n ...,[\n 258\n ...,[\n 0\n ...
20,[\n Winnipeg Jets\n...,[\n 1990\n ...,[\n 26\n ...,[\n 43\n ...,[\n],[\n 0.325\n ...,[\n 260\n ...,[\n 288\n ...,[\n -28\n ...
21,[\n Boston Bruins\n...,[\n 1991\n ...,[\n 36\n ...,[\n 32\n ...,[\n],[\n 0.45\n ...,[\n 270\n ...,[\n 275\n ...,[\n -5\n ...
22,[\n Buffalo Sabres\...,[\n 1991\n ...,[\n 31\n ...,[\n 37\n ...,[\n],[\n 0.388\n ...,[\n 289\n ...,[\n 299\n ...,[\n -10\n ...
23,[\n Calgary Flames\...,[\n 1991\n ...,[\n 31\n ...,[\n 37\n ...,[\n],[\n 0.388\n ...,[\n 296\n ...,[\n 305\n ...,[\n -9\n ...
24,[\n Chicago Blackha...,[\n 1991\n ...,[\n 36\n ...,[\n 29\n ...,[\n],[\n 0.45\n ...,[\n 257\n ...,[\n 236\n ...,[\n 21\n ...