In [9]:
from tqdm import tqdm
import pandas as pd
import requests as r
from bs4 import BeautifulSoup as bs

In [2]:
cardsUrl ="https://www.deckshop.pro/card/list"
response =r.get(cardsUrl)

In [3]:
with open("CardsUrl.html","w") as file:
    file.write(response.text)

In [27]:
baseUrl = "https://www.deckshop.pro"
with open ("CardsUrl.html","r") as file:
    sourceCode = file.read()
    soup = bs(sourceCode, "html.parser")
    cardsUrls = soup.find_all("img",{"class":"card"})
    cardDictioanry = {"Cards Name":[],"Cards Image Urls": []}
    for eachUrl in tqdm( cardsUrls,desc="Downloading Cards",unit="img"):
        cardDictioanry["Cards Name"].append( eachUrl.get("src").split("/")[-1].split(".")[0])
        cardDictioanry["Cards Image Urls"].append(eachUrl.get("src"))
        # tqdm.write(f"Downloading {eachUrl.get('src').split('/')[-1]}...")
        downloadedImage = r.get(baseUrl+eachUrl.get("src"))
        with open("CardsDownload/"+eachUrl.get("src").split("/")[-1],"wb") as img:

            img.write(downloadedImage.content)
    cardDataFrame = pd.DataFrame(cardDictioanry)
    cardDataFrame

Downloading Cards:  22%|██▏       | 118/529 [00:18<01:04,  6.34img/s]

KeyboardInterrupt:

In [20]:
cardDataFrame

      Cards Name                Cards Image Urls
0       Skellies   /img/card_ed_evo/Skellies.png
1      IceSpirit  /img/card_ed_evo/IceSpirit.png
2         Bomber     /img/card_ed_evo/Bomber.png
3           Bats       /img/card_ed_evo/Bats.png
4            Zap        /img/card_ed_evo/Zap.png
..           ...                             ...
524  MightyMiner    /img/card_ed/MightyMiner.png
525  ArcherQueen    /img/card_ed/ArcherQueen.png
526  Goblinstein    /img/card_ed/Goblinstein.png
527         Monk           /img/card_ed/Monk.png
528   BossBandit     /img/card_ed/BossBandit.png

[529 rows x 2 columns]

In [16]:
response = r.get("https://fake-json-api.mock.beeceptor.com/users")
print(response.text)

[
  {
    "id": 1,
    "name": "Clemmie Hansen",
    "company": "McGlynn LLC",
    "username": "Era40",
    "email": "Alfonzo_Barton-Buckridge@hotmail.com",
    "address": "16365 Gislason Shoals",
    "zip": "14811-1784",
    "state": "Nebraska",
    "country": "Heard Island and McDonald Islands",
    "phone": "489-381-9235 x839",
    "photo": "https://json-server.dev/ai-profiles/64.png"
  },
  {
    "id": 2,
    "name": "Thora Faker Attribute Error: person.astName is not supported",
    "company": "Crona, Emard and Batz",
    "username": "Estefania26",
    "email": "Telly73@gmail.com",
    "address": "145 Talon Ranch",
    "zip": "63332-8895",
    "state": "South Dakota",
    "country": "Portugal",
    "phone": "750-878-6183 x6323",
    "photo": "https://json-server.dev/ai-profiles/19.png"
  },
  {
    "id": 3,
    "name": "Jarred McClure",
    "company": "Bartell - Barrows",
    "username": "Cordia.Hamill3",
    "email": "Elliott99@yahoo.com",
    "address": "47560 Giles Avenue",
    "zip": "91494-1190",
    "state": "Connecticut",
    "country": "Malawi",
    "phone": "(754) 932-3335 x324",
    "photo": "https://json-server.dev/ai-profiles/41.png"
  },
  {
    "id": 4,
    "name": "Will McDermott",
    "company": "Krajcik - Fadel",
    "username": "Myrtis_Turner26",
    "email": "Edgar96@yahoo.com",
    "address": "54233 Rectory Lane",
    "zip": "87779-1386",
    "state": "Maine",
    "country": "Turks and Caicos Islands",
    "phone": "848-328-0994 x54471",
    "photo": "https://json-server.dev/ai-profiles/100.png"
  },
  {
    "id": 5,
    "name": "Briana Roberts",
    "company": "Hammes, Bins and Jacobi",
    "username": "Elinore_VonRueden",
    "email": "Alexandra.Roberts34@hotmail.com",
    "address": "24590 Dandre Vista",
    "zip": "84718-9693",
    "state": "Florida",
    "country": "Latvia",
    "phone": "721-484-8088 x779",
    "photo": "https://json-server.dev/ai-profiles/60.png"
  },
  {
    "id": 6,
    "name": "Bernice Schuppe",
    "company": "Fisher - Champlin",
    "username": "Boyd.Renner",
    "email": "Marjorie_Murray92@yahoo.com",
    "address": "67150 Taryn Cove",
    "zip": "07176",
    "state": "Nevada",
    "country": "Democratic People&#x27;s Republic of Korea",
    "phone": "(886) 944-1704 x426",
    "photo": "https://json-server.dev/ai-profiles/64.png"
  },
  {
    "id": 7,
    "name": "Eldridge Beahan",
    "company": "West, Cruickshank and Littel",
    "username": "Esteban.Sawayn",
    "email": "Irving.Schuppe90@gmail.com",
    "address": "558 Muller Valley",
    "zip": "96091",
    "state": "Kentucky",
    "country": "Belarus",
    "phone": "(748) 437-3191 x36422",
    "photo": "https://json-server.dev/ai-profiles/85.png"
  },
  {
    "id": 8,
    "name": "Rosanna Bogan",
    "company": "Larkin - Beatty",
    "username": "Hilda.Klein86",
    "email": "Hilda.Greenholt73@hotmail.com",
    "address": "2603 Koelpin Falls",
    "zip": "01037",
    "state": "Nebraska",
    "country": "Syrian Arab Republic",
    "phone": "1-349-920-6281 x611",
    "photo": "https://json-server.dev/ai-profiles/88.png"
  },
  {
    "id": 9,
    "name": "Parker Crona",
    "company": "Schmidt Inc",
    "username": "Rudolph55",
    "email": "Wallace84@hotmail.com",
    "address": "46996 N 2nd Street",
    "zip": "25612-0427",
    "state": "Connecticut",
    "country": "Bhutan",
    "phone": "(802) 460-1741 x56682",
    "photo": "https://json-server.dev/ai-profiles/46.png"
  },
  {
    "id": 10,
    "name": "Josh Koelpin",
    "company": "Conn Inc",
    "username": "Ewell.Barrows66",
    "email": "Neal68@gmail.com",
    "address": "671 Derby Road",
    "zip": "63482-8009",
    "state": "Arizona",
    "country": "Iceland",
    "phone": "964.905.8969 x205",
    "photo": "https://json-server.dev/ai-profiles/12.png"
  }
]

In [31]:
tableresponse = r.get("https://www.scrapethissite.com/pages/forms/")
with open("TableData.html","w") as file:
    file.write(tableresponse.text)

In [46]:
with open("TableData.html","r") as file:
    sourceCode = file.read()
    soup = bs(sourceCode,"html.parser")
    tableData = soup.find_all("tr")
    tableDataList = []
    for eachRow in tableData:
        cell = eachRow.find_all(["td","th"])
        singleRow=[]
        for eachCell in cell:
            singleRow.append(eachCell.get_text().strip())
        tableDataList.append(singleRow)

In [47]:
tableDF = pd.DataFrame(tableDataList[1:],columns=tableDataList[0])

In [48]:
tableDF

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,,0.388,292,278,14
2,Calgary Flames,1990,46,26,,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,,0.425,273,298,-25
5,Edmonton Oilers,1990,37,37,,0.463,272,272,0
6,Hartford Whalers,1990,31,38,,0.388,238,276,-38
7,Los Angeles Kings,1990,46,24,,0.575,340,254,86
8,Minnesota North Stars,1990,27,39,,0.338,256,266,-10
9,Montreal Canadiens,1990,39,30,,0.487,273,249,24
10,New Jersey Devils,1990,32,33,,0.4,272,264,8
11,New York Islanders,1990,25,45,,0.312,223,290,-67
12,New York Rangers,1990,36,31,,0.45,297,265,32
13,Philadelphia Flyers,1990,33,37,,0.412,252,267,-15
14,Pittsburgh Penguins,1990,41,33,,0.512,342,305,37
15,Quebec Nordiques,1990,16,50,,0.2,236,354,-118
16,St. Louis Blues,1990,47,22,,0.588,310,250,60
17,Toronto Maple Leafs,1990,23,46,,0.287,241,318,-77
18,Vancouver Canucks,1990,28,43,,0.35,243,315,-72
19,Washington Capitals,1990,37,36,,0.463,258,258,0
20,Winnipeg Jets,1990,26,43,,0.325,260,288,-28
21,Boston Bruins,1991,36,32,,0.45,270,275,-5
22,Buffalo Sabres,1991,31,37,,0.388,289,299,-10
23,Calgary Flames,1991,31,37,,0.388,296,305,-9
24,Chicago Blackhawks,1991,36,29,,0.45,257,236,21