In [2]:
from tqdm import tqdm
import pandas as pd
import requests as r
from bs4 import BeautifulSoup as bs

/Users/muhammadahmadhumayoun/PyCharmMiscProject/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:
cardsUrl ="https://www.deckshop.pro/card/list"
response =r.get(cardsUrl)

In [3]:
with open("CardsUrl.html","w") as file:
    file.write(response.text)

In [27]:
baseUrl = "https://www.deckshop.pro"
with open ("CardsUrl.html","r") as file:
    sourceCode = file.read()
    soup = bs(sourceCode, "html.parser")
    cardsUrls = soup.find_all("img",{"class":"card"})
    cardDictioanry = {"Cards Name":[],"Cards Image Urls": []}
    for eachUrl in tqdm( cardsUrls,desc="Downloading Cards",unit="img"):
        cardDictioanry["Cards Name"].append( eachUrl.get("src").split("/")[-1].split(".")[0])
        cardDictioanry["Cards Image Urls"].append(eachUrl.get("src"))
        # tqdm.write(f"Downloading {eachUrl.get('src').split('/')[-1]}...")
        downloadedImage = r.get(baseUrl+eachUrl.get("src"))
        with open("CardsDownload/"+eachUrl.get("src").split("/")[-1],"wb") as img:

            img.write(downloadedImage.content)
    cardDataFrame = pd.DataFrame(cardDictioanry)
    cardDataFrame

Downloading Cards:  22%|██▏       | 118/529 [00:18<01:04,  6.34img/s]

KeyboardInterrupt:

In [20]:
cardDataFrame

      Cards Name                Cards Image Urls
0       Skellies   /img/card_ed_evo/Skellies.png
1      IceSpirit  /img/card_ed_evo/IceSpirit.png
2         Bomber     /img/card_ed_evo/Bomber.png
3           Bats       /img/card_ed_evo/Bats.png
4            Zap        /img/card_ed_evo/Zap.png
..           ...                             ...
524  MightyMiner    /img/card_ed/MightyMiner.png
525  ArcherQueen    /img/card_ed/ArcherQueen.png
526  Goblinstein    /img/card_ed/Goblinstein.png
527         Monk           /img/card_ed/Monk.png
528   BossBandit     /img/card_ed/BossBandit.png

[529 rows x 2 columns]

In [16]:
response = r.get("https://fake-json-api.mock.beeceptor.com/users")
print(response.text)

[
  {
    "id": 1,
    "name": "Clemmie Hansen",
    "company": "McGlynn LLC",
    "username": "Era40",
    "email": "Alfonzo_Barton-Buckridge@hotmail.com",
    "address": "16365 Gislason Shoals",
    "zip": "14811-1784",
    "state": "Nebraska",
    "country": "Heard Island and McDonald Islands",
    "phone": "489-381-9235 x839",
    "photo": "https://json-server.dev/ai-profiles/64.png"
  },
  {
    "id": 2,
    "name": "Thora Faker Attribute Error: person.astName is not supported",
    "company": "Crona, Emard and Batz",
    "username": "Estefania26",
    "email": "Telly73@gmail.com",
    "address": "145 Talon Ranch",
    "zip": "63332-8895",
    "state": "South Dakota",
    "country": "Portugal",
    "phone": "750-878-6183 x6323",
    "photo": "https://json-server.dev/ai-profiles/19.png"
  },
  {
    "id": 3,
    "name": "Jarred McClure",
    "company": "Bartell - Barrows",
    "username": "Cordia.Hamill3",
    "email": "Elliott99@yahoo.com",
    "address": "47560 Giles Avenue",
    "zip": "91494-1190",
    "state": "Connecticut",
    "country": "Malawi",
    "phone": "(754) 932-3335 x324",
    "photo": "https://json-server.dev/ai-profiles/41.png"
  },
  {
    "id": 4,
    "name": "Will McDermott",
    "company": "Krajcik - Fadel",
    "username": "Myrtis_Turner26",
    "email": "Edgar96@yahoo.com",
    "address": "54233 Rectory Lane",
    "zip": "87779-1386",
    "state": "Maine",
    "country": "Turks and Caicos Islands",
    "phone": "848-328-0994 x54471",
    "photo": "https://json-server.dev/ai-profiles/100.png"
  },
  {
    "id": 5,
    "name": "Briana Roberts",
    "company": "Hammes, Bins and Jacobi",
    "username": "Elinore_VonRueden",
    "email": "Alexandra.Roberts34@hotmail.com",
    "address": "24590 Dandre Vista",
    "zip": "84718-9693",
    "state": "Florida",
    "country": "Latvia",
    "phone": "721-484-8088 x779",
    "photo": "https://json-server.dev/ai-profiles/60.png"
  },
  {
    "id": 6,
    "name": "Bernice Schuppe",
    "company": "Fisher - Champlin",
    "username": "Boyd.Renner",
    "email": "Marjorie_Murray92@yahoo.com",
    "address": "67150 Taryn Cove",
    "zip": "07176",
    "state": "Nevada",
    "country": "Democratic People&#x27;s Republic of Korea",
    "phone": "(886) 944-1704 x426",
    "photo": "https://json-server.dev/ai-profiles/64.png"
  },
  {
    "id": 7,
    "name": "Eldridge Beahan",
    "company": "West, Cruickshank and Littel",
    "username": "Esteban.Sawayn",
    "email": "Irving.Schuppe90@gmail.com",
    "address": "558 Muller Valley",
    "zip": "96091",
    "state": "Kentucky",
    "country": "Belarus",
    "phone": "(748) 437-3191 x36422",
    "photo": "https://json-server.dev/ai-profiles/85.png"
  },
  {
    "id": 8,
    "name": "Rosanna Bogan",
    "company": "Larkin - Beatty",
    "username": "Hilda.Klein86",
    "email": "Hilda.Greenholt73@hotmail.com",
    "address": "2603 Koelpin Falls",
    "zip": "01037",
    "state": "Nebraska",
    "country": "Syrian Arab Republic",
    "phone": "1-349-920-6281 x611",
    "photo": "https://json-server.dev/ai-profiles/88.png"
  },
  {
    "id": 9,
    "name": "Parker Crona",
    "company": "Schmidt Inc",
    "username": "Rudolph55",
    "email": "Wallace84@hotmail.com",
    "address": "46996 N 2nd Street",
    "zip": "25612-0427",
    "state": "Connecticut",
    "country": "Bhutan",
    "phone": "(802) 460-1741 x56682",
    "photo": "https://json-server.dev/ai-profiles/46.png"
  },
  {
    "id": 10,
    "name": "Josh Koelpin",
    "company": "Conn Inc",
    "username": "Ewell.Barrows66",
    "email": "Neal68@gmail.com",
    "address": "671 Derby Road",
    "zip": "63482-8009",
    "state": "Arizona",
    "country": "Iceland",
    "phone": "964.905.8969 x205",
    "photo": "https://json-server.dev/ai-profiles/12.png"
  }
]

In [31]:
tableresponse = r.get("https://www.scrapethissite.com/pages/forms/")
with open("TableData.html","w") as file:
    file.write(tableresponse.text)

In [46]:
with open("TableData.html","r") as file:
    sourceCode = file.read()
    soup = bs(sourceCode,"html.parser")
    tableData = soup.find_all("tr")
    tableDataList = []
    for eachRow in tableData:
        cell = eachRow.find_all(["td","th"])
        singleRow=[]
        for eachCell in cell:
            singleRow.append(eachCell.get_text().strip())
        tableDataList.append(singleRow)

In [47]:
tableDF = pd.DataFrame(tableDataList[1:],columns=tableDataList[0])

In [48]:
tableDF

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,,0.388,292,278,14
2,Calgary Flames,1990,46,26,,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,,0.425,273,298,-25
5,Edmonton Oilers,1990,37,37,,0.463,272,272,0
6,Hartford Whalers,1990,31,38,,0.388,238,276,-38
7,Los Angeles Kings,1990,46,24,,0.575,340,254,86
8,Minnesota North Stars,1990,27,39,,0.338,256,266,-10
9,Montreal Canadiens,1990,39,30,,0.487,273,249,24
10,New Jersey Devils,1990,32,33,,0.4,272,264,8
11,New York Islanders,1990,25,45,,0.312,223,290,-67
12,New York Rangers,1990,36,31,,0.45,297,265,32
13,Philadelphia Flyers,1990,33,37,,0.412,252,267,-15
14,Pittsburgh Penguins,1990,41,33,,0.512,342,305,37
15,Quebec Nordiques,1990,16,50,,0.2,236,354,-118
16,St. Louis Blues,1990,47,22,,0.588,310,250,60
17,Toronto Maple Leafs,1990,23,46,,0.287,241,318,-77
18,Vancouver Canucks,1990,28,43,,0.35,243,315,-72
19,Washington Capitals,1990,37,36,,0.463,258,258,0
20,Winnipeg Jets,1990,26,43,,0.325,260,288,-28
21,Boston Bruins,1991,36,32,,0.45,270,275,-5
22,Buffalo Sabres,1991,31,37,,0.388,289,299,-10
23,Calgary Flames,1991,31,37,,0.388,296,305,-9
24,Chicago Blackhawks,1991,36,29,,0.45,257,236,21

In [4]:
baseUrlForHockeyTeamWebsite= "https://www.scrapethissite.com/pages/forms/?page_num=1"

for i in range(1,25):
    response = r.get(baseUrlForHockeyTeamWebsite+f"&page_num={i}")
    with open(f"/Users/muhammadahmadhumayoun/Downloads/GithubTutorial/AdvancePythonClass/AdvancePythonClassRepo/scraped_data/web_pages/HocketTeamPages/HockeyTeamWebsiteData{i}.html","w") as file:
        file.write(response.text)

In [36]:
tableDataList = []
for currentPage in range(1,25):
    hockeyHtmlPage = f"/Users/muhammadahmadhumayoun/Downloads/GithubTutorial/AdvancePythonClass/AdvancePythonClassRepo/scraped_data/web_pages/HocketTeamPages/HockeyTeamWebsiteData{currentPage}.html"
    with open(hockeyHtmlPage,"r") as file:
        print(f"Reading {currentPage} page...")
        sourceCode = file.read()
        soup = bs(sourceCode,"html.parser")
        tableData = soup.find_all("tr")
        for eachRow in tableData:
            if (currentPage == 1):
                cell = eachRow.find_all(["td","th"])
            else:
                cell = eachRow.find_all("td")
            singleRow=[]
            for eachCell in cell:
                singleRow.append(eachCell.get_text().strip())
            tableDataList.append(singleRow)
            print(len(tableDataList))
        # print(tableDataList)
        hocketDf = pd.DataFrame(tableDataList[1:],columns=tableDataList[0])

Reading 1 page...
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
Reading 2 page...
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
Reading 3 page...
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
Reading 4 page...
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
Reading 5 page...
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
Reading 6 page...
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
Reading 7 page...
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
Reading 8 page...
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
Reading 9 page...
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
Reading 10 page...
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
Reading 11 page...
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
Reading 12 page...
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
Reading 13 page...
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
Reading 14 page...
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
Reading 15 page...
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
Reading 16 page...
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
Reading 17 page...
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
Reading 18 page...
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
Reading 19 page...
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
Reading 20 page...
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
Reading 21 page...
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
Reading 22 page...
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
Reading 23 page...
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
Reading 24 page...
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624

In [37]:
print(len(tableDataList))
len(hocketDf)

624

623

In [38]:
hocketDf

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,,0.388,292,278,14
2,Calgary Flames,1990,46,26,,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,,0.425,273,298,-25
...,...,...,...,...,...,...,...,...,...
618,Winnipeg Jets,1990,26,43,,0.325,260,288,-28
619,Boston Bruins,1991,36,32,,0.45,270,275,-5
620,Buffalo Sabres,1991,31,37,,0.388,289,299,-10
621,Calgary Flames,1991,31,37,,0.388,296,305,-9
622,Chicago Blackhawks,1991,36,29,,0.45,257,236,21